apiVersion: v1
kind: Pod
spec:
  containers:
  - name: base
    image: apache/airflow:2.10.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args: ["sleep infinity"]
  restartPolicy: OnFailure
