version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: localhost
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['initial_root_password'] = 'StrongInitialPassword123!'
        gitlab_rails['gitlab_shell_ssh_port'] = 22
        nginx['listen_port'] = 80
        gitlab_kas['enable'] = true
        gitlab_kas['external_url'] = 'ws://localhost:8090'
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS (opcional, para usar SSL)
      - "22:22"    # SSH
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
    networks:
      - gitlab-network

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

networks:
  gitlab-network:
    driver: bridge

