apiVersion: batch/v1
kind: CronJob
metadata:
  name: iris-pipeline-cronjob
spec:
  schedule: "0 0 * * *" # Ejemplo: se ejecuta todos los días a medianoche
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: iris-pipeline
            image: rhobtor/iris-pipeline
          restartPolicy: Never
