apiVersion: batch/v1
kind: Job
metadata:
  name: iris-pipeline-job
spec:
  template:
    metadata:
      labels:
        app: iris-pipeline
    spec:
      containers:
      - name: iris-pipeline
        image: rhobtor/iris-pipeline
        imagePullPolicy: IfNotPresent
      restartPolicy: OnFailure
